# Development stage
FROM node:14 AS build-stage

# 경로 설정하기
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY package.json ./
COPY package-lock.json ./
RUN npm install --legacy-peer-deps

# 전체 애플리케이션 코드 복사
COPY . ./

RUN npm run build

# 애플리케이션 실행을 위한 명령
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
COPY nginx/dev/nginx.conf /etc/nginx/nginx.conf
COPY nginx/dev/localhost.crt /etc/nginx/localhost.crt
COPY nginx/dev/localhost.key /etc/nginx/localhost.key

EXPOSE 443
EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]
