version: '3.8'

services:
  server:
    build: 
        context: ./client
        dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod

  client:
    volumes:
        - ./certbot/conf/letsencrypt:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
        - ./server/media:/app/media

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf/letsencrypt:/etc/letsencrypt
      - ./client/build:/usr/share/nginx/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - client