# Generated by Django 4.2.9 on 2024-03-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_auto_20240125_1110"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
