# Generated by Django 4.2.9 on 2024-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="approve",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="product",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="ready",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="tid",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="user",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="uuid",
        ),
        migrations.AddField(
            model_name="purchase",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="purchase",
            name="imp_uid",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AddField(
            model_name="purchase",
            name="merchant_uid",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AddField(
            model_name="purchase",
            name="status",
            field=models.CharField(default="anonymous", max_length=20),
        ),
        migrations.DeleteModel(
            name="PurchaseApprovalResult",
        ),
    ]
