# Generated by Django 4.2.9 on 2024-02-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_product_sizes"),
        ("purchase", "0002_remove_purchase_approve_remove_purchase_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="buyer_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="buyer_email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="buyer_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="buyer_postcode",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="buyer_tel",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("size", models.CharField(max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.purchase",
                    ),
                ),
            ],
        ),
    ]
