# Generated by Django 4.2.9 on 2024-02-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0003_purchase_buyer_address_purchase_buyer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="buyer_detailAddress",
            field=models.CharField(default="상세주소", max_length=255, null=True),
        ),
    ]
