# Generated by Django 4.2.9 on 2024-03-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_product_sizes"),
        ("purchase", "0005_alter_purchase_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.size"
            ),
        ),
    ]
