# Generated by Django 3.2.10 on 2024-01-03 08:52

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('아우터', 'outer'), ('상의', 'top'), ('하의', 'pants'), ('신발', 'shoes'), ('악세사리', 'accessory')], default='상의', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='상품 이미지', null=True, upload_to=common.utils.rename_image_file_to_uuid),
        ),
    ]
