# Generated by Django 3.2.10 on 2024-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
