# Generated by Django 3.2.10 on 2024-01-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240125_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='도로명주소', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='detailAddress',
            field=models.CharField(default='상세주소', help_text='상세주소', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='postCode',
            field=models.CharField(default='우편번호', max_length=100),
        ),
    ]
