# Generated by Django 3.2.10 on 2023-12-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231226_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='유저 이메일', max_length=50, unique=True),
        ),
    ]
