# Generated by Django 3.2.10 on 2024-01-10 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
