# Generated by Django 3.2.10 on 2024-01-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutstandingToken',
        ),
    ]
