# Generated by Django 3.2.10 on 2024-01-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_outstandingtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutstandingToken',
        ),
    ]
