# Generated by Django 3.2.10 on 2024-01-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='product_sizes', through='products.ProductSize', to='products.Size'),
        ),
    ]
